### PR TITLE
Fix cordova id

### PR DESCRIPTION
**Pull request by gabfiocchi**
@shaders:
you forgot to change the rest of the id there as 'com.pushwoosh.plugins.pushwoosh' hence the name continues appearing poorly in this Pull Request I tried it and get the name right
{
      "locator": "https://github.com/gabfiocchi/pushwoosh-phonegap-plugin.git",
      **"id": "pushwoosh-cordova-plugin"**
 }

Thanks!

### CODE REVIEW

**Comment by gabfiocchi** [comment]
This issue it's continue to #164 and #165

**Comment by shaders** [comment]
Merged but new plugin id broke backward compatibility.

**Comment by gabfiocchi** [comment]
Yes, but only when they want to do a fresh install or restore some versioning, it is time to take advantage of the fixes that have made :)

**Comment by gabfiocchi** [comment]
Thanks @shaders !

**Pull request merged**
